#+TITLE: Repeated String
#+AUTHOR: Dat Adithya
#+TAGS: @wit @strings

* WHAT IS THIS? :@wit:
Another program on working with strings and noting down the frequency of usage in the string.
The question is designed to help you work with frequencies and string traversing.

It requires you to provide a method that does so.

* Repeated String :@strings:
**Question**
There is a string, s, of lowercase English letters that is repeated infinitely many times. Given an integer, n, find and print the number of letter a's in the first n letters of the infinite string.

**Function Description**
Complete the repeatedString function in the editor below.

repeatedString has the following parameter(s):

_s_: a string to repeat
_n_: the number of characters to consider

**Returns**
_int_: the frequency of a in the substring

#+HEADERS: :classname RepeatedString
#+BEGIN_SRC java :results silent
class RepeatedString {

    /*
     ,* Complete the 'repeatedString' function below.
     ,*
     ,* The function is expected to return a LONG_INTEGER.
     ,* The function accepts following parameters:
     ,*  1. STRING s
     ,*  2. LONG_INTEGER n
     ,*/

    public static long repeatedString(String s, long n) {
        // Initializing the variables
        long size = s.length(), repeated = n/size;

        // Number of characters left
        long left = n - (size * repeated);
        int extra = 0;

        // Number of characters in the repeated string
        int count = 0;
        for(int i = 0; i < size; i++){
            if(s.charAt(i) == 'a'){
                ++count;
            }
        }

        // Number of characters in the partially repeated string
        for(int i = 0; i < left; i++){
            if(s.charAt(i) == 'a'){
                ++extra;
            }
        }

        // Totalling the repeated and remaining strings
        repeated = (repeated * count) + extra;

        // Returning the number of a's
        return repeated;
    }

    public static void main(String[] args){
        long numA = repeatedString("aba", 10);
        System.out.println("The number of a's in the repeated string : " + numA);
    }
}
#+END_SRC

Link to the question => [[https://www.hackerrank.com/challenges/repeated-string/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=warmup&h_r=next-challenge&h_v=zen][Repeated String on Hackerrank]].
